name: Update README


on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:  # Allows you to run the workflow manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Update README
      run: |
        python readme.py

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-update README

